# Generated by Django 5.1.2 on 2024-11-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_post_details_post_alt_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='alt_phone_number',
            new_name='alternative_phone_number',
        ),
    ]
